### ISSUE TITLE
Add rack view links in hwdoc single equipment view and equipment search view

### ISSUE THREAD

**Issue by irregulator** [servermon/servermon#195]
I think it would be very helpful in terms of UX and navigation if in single equipment view and equipment search view we had hyperlinks to the relevant rack.

For example in 
![servermon_equipment](https://cloud.githubusercontent.com/assets/6627859/23993859/ed5f855e-0a4a-11e7-96e2-61ff33c5014a.png) 

rackunit value 'YCR0802' could link to the rackunit's rack view.

The same goes for the search view
![servermon_equipment_search](https://cloud.githubusercontent.com/assets/6627859/23993962/6f170ebe-0a4b-11e7-96e6-2258e10edd8f.png) where the Rack column value 'YCR08' could link to that rack.

I hope that makes sense!

**Comment by akosiaris** [comment]
I concur. Already done in PR #196, you can see what that would look like in 

https://servermon.herokuapp.com/hwdoc/equipment/831/ and https://servermon.herokuapp.com/search?q=DLTE2ZRTUGT1AP5

respectively

Unless you have a comment I 'll proceed and merge it.

**Comment by irregulator** [comment]
nice, thanks!
