### ISSUE TITLE
search by RU broken after adding prefix infront of the RU number

### ISSUE THREAD

**Issue by leonkons** [servermon/servermon#86]
after adding a prefix in the rack name we lost the capability to search for a specific RU in the web interface. We are still able to search for the hall rack. Thus searching e.g. for YAR312 will not bring any result but when searching for YAR31 will show all the equipment in that rack

Below you can find an example of the change we implemented
e.g. R14 is now YAR14 
Y = Ministry of Education, A = area A, R14 = Rack 14

![yar31](https://cloud.githubusercontent.com/assets/10828654/6077183/0abae40e-adf5-11e4-8a7f-400e2ce035c7.png)
![yar3125](https://cloud.githubusercontent.com/assets/10828654/6077184/0ad7e1d0-adf5-11e4-94e2-d64197cdd11a.png)

**Comment by akosiaris** [comment]
This is due to the regular expression in 

https://github.com/servermon/servermon/blob/master/servermon/hwdoc/functions.py#L71

Probably a ^(\w*\d\d)[Uu]?(\d\d)$ will do the trick (* instead of ?)
